apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatbot-client
  template:
    metadata:
      labels:
        app: chatbot-client
    spec:
      containers:
        - name: chatbot-client-container
          image: eduardo123456789/chatbot-client-image:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-client-service
spec:
  selector:
    app: chatbot-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
