# Use a imagem oficial do Nginx
FROM nginx:latest

# Copie as configurações personalizadas do Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Defina o diretório de trabalho como /usr/share/nginx/html
WORKDIR /usr/share/nginx/html

# Copie os arquivos estáticos para o diretório padrão do Nginx
COPY static/ static/

# Exponha a porta 80 para acessar o Nginx
EXPOSE 80

# Comando para iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]
