apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-client
  template:
    metadata:
      labels:
        app: chatbot-client
    spec:
      containers:
      - name: chatbot-client
        image: eduardo123456789/chatbot-sd-client
        ports:
        - containerPort: 5001
