version: '3'

services:
  server:
    build:
      context: server
    ports:
      - "5000"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - "80:80"
  
  client:
    build:
      context: client
    ports:
      - "5001:5001"    