apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatbot-server
  template:
    metadata:
      labels:
        app: chatbot-server
    spec:
      containers:
        - name: chatbot-server-container
          image: eduardo123456789/chatbot-server-image:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-server-service
spec:
  selector:
    app: chatbot-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
