apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-server
  template:
    metadata:
      labels:
        app: chatbot-server
    spec:
      containers:
      - name: chatbot-server
        image: eduardo123456789/chatbot-sd-server
        ports:
        - containerPort: 5000
